version: "3"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - "$PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD/:/usr/share/nginx/"
    networks:
      - app_net
    container_name: "compose-nginx"

  php:
    build: ./php
    image: php:fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "$PWD/:/var/www/"
    networks:
      - app_net
    container_name: "compose-php"

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    networks:
      app_net:
        ipv4_address: 10.10.10.1
    container_name: "compose-mysql"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
